### PR TITLE
add ray-tune packages

### PR DESCRIPTION
**Pull request by MichaelClifford**
Adding additional ray packages to Pipfile and Pipfile.lock needed to use the Ray Tune tooling with Jupyterhub.

### CODE REVIEW

**Comment by MichaelClifford** [comment]
cc @harshad16 @erikerlandson

**Comment by harshad16** [comment]
@MichaelClifford  did you try installing these in the jupyterhub notebook directly and tested it ?

**Comment by MichaelClifford** [comment]
These packages need to exist in both the notebook nodes and the worker nodes for them to function properly. So installing in the notebook directly does not work as it does not update the workers (right?). It still needs to be tested in a jupyterhub environment.

**Comment by erikerlandson** [comment]
@MichaelClifford  in general it's best to assume that packages installed on a nb should also be installed on the worker images.  I think there might be exceptions to that but it's not worth the effort of figuring out what those exceptions are.

**Pull request merged**
